name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches: [master, main]
    tags: ['*']

permissions:
  contents: read
  packages: read

jobs:
  deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - id: meta
        run: |
          REPO=${{ github.repository }}
          if [[ "${GITHUB_REF}" == refs/heads/main ]]; then
            echo "tags=$REPO:latest" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            git fetch origin main
            MAIN_COMMIT=$(git rev-parse origin/main)
            if [ "$GITHUB_SHA" = "$MAIN_COMMIT" ]; then
              echo "tags=$REPO:$TAG_NAME,$REPO:latest" >> $GITHUB_OUTPUT
            else
              echo "tags=$REPO:$TAG_NAME" >> $GITHUB_OUTPUT
            fi
          fi

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
